apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Values.app }}
spec:
  schedule: "0 */1 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          volumes:
            - name: svc-acct
              secret:
                secretName: infra-admin-service-account
          containers:
            - name: {{ .Values.app }}
              image: {{ .Values.docker_image }}
              args:
                - "-storageLogsBucket"
                - "{{.Values.storageLogsBucket}}"
                - "-bucketSizesFile"
                - "{{.Values.bucketSizesFile}}"
              env:
                - name: APP
                  value: {{.Chart.Name}}
                - name: GCP_PROJECT
                  value: {{.Values.gcp_project}}
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /creds/infra-admin.json
              volumeMounts:
                - name: svc-acct
                  mountPath: /creds
                  readOnly: true